### PR TITLE
add version to filename output

### PR DESCRIPTION
**Pull request by SmithKevin**
To keep consistant with `npm pack` which formats its filename as `<name>-<version>.tgz`

### CODE REVIEW

**Comment by SmithKevin** [comment]
bump.  @mwasplund Curious on your thoughts

**Review by JasonMongue — APPROVED** [review]

**Comment by JasonMongue** [comment]
@mwasplund Would love this PR merged in.

**Comment by mwasplund** [comment]
Sorry, I was not getting notifications on this. I like the idea, but our current usage requires the file name to be the same each time. Can we throw this behind an optional parameter?

**Comment by NatXenith** [comment]
I think it would be great to at least have this as an optional parameter at least.

**Comment by mwasplund** [comment]
Another PR has the same changes with a flag to optionally enable the version tag

**Pull request closed without merging**
