### PR TITLE
Add version to filename

### PR DESCRIPTION
**Pull request by xpro666**
Add package varsion to default output archive name, same as npm pack do it

### CODE REVIEW

**Comment by mwasplund** [comment]
Please see my comments in the other PR that makes the same change. My setup requires that there is no version tag so the file name is the same with each release. If you feel this will be useful then the version tag needs to be behind an optional flag that defaults to off. Thanks!

**Comment by xpro666** [comment]
Hi, i add new option for adding version to output file name

**Review by mwasplund — APPROVED** [review]
Looks good to me

**Comment by gentarooka** [comment]
Hey, @mwasplund 

When will this PR be merged? 
Looking forward to seeing a new version!

**Comment by mwasplund** [comment]
Sorry I figured xpro could close the pr after I approved. It should be live soon.

**Pull request merged**
